### ISSUE TITLE
Notificaition icon issue

### ISSUE THREAD

**Issue by VipulNarkhede** [freshdesk/hotline-android#10]
I am not able to set the background color behind notification icon on device having android version5.0 and above.

From Android 5.0 and above, we can set background color using method NotificationCompatBuilder.setColor behind notification icon.

Please resolve the issue.

**Comment by tryprasannan** [comment]
@VipulNarkhede Please include the color as a resource in your app's resources (colors.xml)
`<color name="hotline_notification_accent_color">@color/green</color>`
Please reopen if this doesn't work.
