### ISSUE TITLE
Missing/Bad FileProvider in v1.2.1

### ISSUE THREAD

**Issue by kshitij-sminq** [freshdesk/hotline-android#16]
In hotline android sdk v1.2.1, I get an error toast message saying "missing/bad FileProvider for hotline. Camera capture will fail in devices running Nougat or later (error code 354)." Could you please explain what issue this is and the fix for this? Thank you.

**Comment by tryprasannan** [comment]
@kshitij-sminq For apps targeting Android 7.0+, Hotline SDK requires a file provider to share the file with camera app for camera capture. Please include the FileProvider element in your app's AndroidManifest.xml. Please refer to [section 1.1 of the integration guide](https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps#android_24) for more information.
