### ISSUE TITLE
Cannot resolve classes in v1.2.1

### ISSUE THREAD

**Issue by kshitij-sminq** [freshdesk/hotline-android#17]
In v1.2.1, the following classes cannot be resolved:

import com.freshdesk.hotline.FaqOptions;
import com.freshdesk.hotline.Hotline;

**Comment by tryprasannan** [comment]
@kshitij-sminq Just to be sure, the version is `1.2.1` and not `v1.2.1`. Can you confirm you are using the correct version ?
Eg: **compile 'com.github.freshdesk:hotline-android:1.2.1'**

**Comment by kshitij-sminq** [comment]
@tryprasannan yes I am using **compile 'com.github.freshdesk:hotline-android:1.2.+'** as suggested in the docs. I have tried cleaning and rebuilding the project multiple times too. I have reverted to version 1.2.0 for now.

**Comment by tryprasannan** [comment]
@kshitij-sminq Closing this issue as it is working per your confirmation at https://support.freshdesk.com/helpdesk/tickets/992227
Please reopen if this is still an issue for you.
