### ISSUE TITLE
android 7 会crash

### ISSUE THREAD

**Issue by LeoYe168** [freshdesk/hotline-android#18]
Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.daigou.sg/cache/tmp_pics/pic_1490807007065291825884.jpg exposed beyond app through ClipData.Item.getUri()

**Comment by tryprasannan** [comment]
@LeoYe168 Can you confirm what version of SDK you have integrated ?

**Comment by LeoYe168** [comment]
@tryprasannan  compile 'com.github.freshdesk:hotline-android:1.0.+'

**Comment by tryprasannan** [comment]
@LeoYe168 We've released a fix for this some time ago. Recommend you try this with the current latest version 1.2.1. Please refer our [integration guide](https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps#android_24) here for further instructions

**Comment by tryprasannan** [comment]
@LeoYe168  Closing this now. If you're still facing this issue, please feel free to reopen this issue.

**Comment by LeoYe168** [comment]
thanks, but i can not reproduce bug，
