### ISSUE TITLE
Typo in styles.xml

### ISSUE THREAD

**Issue by vibin** [freshdesk/hotline-android#20]
"Survey", not "Survery". Just pointing out. https://github.com/freshdesk/hotline-android/blob/master/hotline_sdk/src/main/res/values/styles.xml

(thought I made a typing mistake myself, had to check the source to realize it's not me!)

**Comment by tryprasannan** [comment]
@vibinr Thanks for pointing this out. We'll fix this in the next release.

**Comment by MuthuFD** [comment]
@vibinr Thanks for pointing it out. We have fixed it version 1.2.4.
