### ISSUE TITLE
HotlineComponentNotFoundException

### ISSUE THREAD

**Issue by kshitij-sminq** [freshdesk/hotline-android#26]
I am getting the following exception frequently 

`Caused by com.freshdesk.hotline.exception.HotlineComponentNotFoundException: Component of Hotline SDK not found in your app's AndroidManifest.xml + (com.freshdesk.hotline.receiver.HotlineReceiver missing!)
       at com.freshdesk.hotline.util.o.L(Unknown Source)
       at com.freshdesk.hotline.Hotline.init(Unknown Source)`

I have added your proguard configuration as mentioned in the docs. What am I missing here?

**Comment by tryprasannan** [comment]
@kshitij-sminq We've noticed this happening randomly on specific manufacturers' devices running 7.0+. Can you confirm the device manufacturer and the OS version this is happening on ?

**Comment by kshitij-sminq** [comment]
Here's a link to the crash info http://crashes.to/s/2f1cfecadc7

**Comment by tryprasannan** [comment]
@kshitij-sminq Thanks for the logs. We're working on a fix for this. Will update this thread once it's live.

**Comment by MuthuFD** [comment]
@kshitij-sminq We have fixed this issue in version 1.2.4
