### ISSUE TITLE
Icons not following MaterialDesign spec

### ISSUE THREAD

**Issue by okmanideep** [freshdesk/hotline-android#3]
`ImageView` size needs to be `48dp` and padding needs to `12dp`. So the resultant icon size is `24dp`. This is not a hard rule like every thing in the Material Spec, but it looks way better that way.

**Comment by tryprasannan** [comment]
@manidesto We'll take it up internally and see how we can align to the spec. You can override the dimensions of most of the icons. They are listed here -> [dimens.xml](https://github.com/freshdesk/hotline-android/blob/master/hotline_sdk/src/main/res/values/dimens.xml)

**Comment by okmanideep** [comment]
@tryprasannan awesome. Thanks.
