### ISSUE TITLE
How to change the "Inbox" title in chat screen

### ISSUE THREAD

**Issue by ManojMadanmohan** [freshdesk/hotline-android#34]
![zophop_hotline_chat_screen](https://user-images.githubusercontent.com/17469318/33160521-28fcdfd0-d043-11e7-9876-80eb3e44fc01.png)

Wanted to now how can I change the "Inbox" title in chat screen as shown above?

**Comment by tryprasannan** [comment]
@ManojMadanmohan This is the message channel name/title from the backend. You can update the same by logging into your agent portal and update the same in Settings > Message Channels

**Comment by ManojMadanmohan** [comment]
Thanks @tryprasannan
