### ISSUE TITLE
CONNECTIVITY_CHANGE implicit broadcast

### ISSUE THREAD

**Issue by sagar-viradiya** [freshdesk/hotline-android#38]
If you target API level 27 there is restriction on implicit broadcast. Since HotlineNetworkChangeReceiver listen for connectivity change this won't work if SDK consumer target to API level 27. Any plan to handle this ?

**Comment by tryprasannan** [comment]
@sagar-viradiya Thanks for reaching out to us. This affects only the auto retry mechanism for messages when the app targets the later versions of OS. ~That said, we'll look at ways to improve the experience.~ 

Edit: We no longer support this product, would recommend you try out our new and improved product [Freshchat](https://freshchat.com)
