### ISSUE TITLE
Camera orientation issue

### ISSUE THREAD

**Issue by iangmaia** [freshdesk/hotline-android#8]
When a user sends a landscape image, it is shown with the wrong orientation on the chat.
We tried it with a Samsung S4.

**Comment by hrishikesh-p** [comment]
@iangmaia Samsung devices do seem to have a different behaviour when it comes to camera orientation. We will have a fix for this in the next SDK update.

**Comment by tryprasannan** [comment]
@iangmaia This has been addressed in [1.0.15](https://github.com/freshdesk/hotline-android/releases/tag/1.0.15). Please update to the latest version. Marking this as closed.
