### ISSUE TITLE
SDK messing with Android API

### ISSUE THREAD

**Issue by nanako-sen** [freshdesk/hotline-android#9]
Hello,

I have the weirdest issue I have every encountered.
I have nested fragments in my app and without integrating the SDK getChildFragmentManager() works like expected: getChildFragmentManager().findFragmentById(R.id.fragment) returns the fragment , getFragmentManager().findFragmentById(R.id.fragment) returns null.
By just adding the SDK as dependency getChildFragmentManager().findFragmentById(R.id.fragment) returns null but getFragmentManager().findFragmentById(R.id.fragment) returns the fragment. 

Also Android studio highlights a warning for an activity extending ActionBarActivity that super.onCreate() has multiple implementations and therefor "Overriding method should call super.onCreate()" on onCreate(Bundle saveInstanceState). Which, again, does not happen when the SDK is not added. 

I can't stop wondering if your SDK is not doing something strange. If you need more information please let me know. Would be great if you can shine some light on this, I am scratching my head. 

Gradle (simplified):

```
android {
    compileSdkVersion 21
    buildToolsVersion "23.0.2"
    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}
repositories {
    mavenCentral()
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.google.android.gms:play-services:7.0.0'
    compile 'com.github.freshdesk:hotline-android:1.0.14'
}
```

**Comment by srikrishnan-ganesan** [comment]
Hi Nano, our team will investigate this at the earliest.

**Comment by tryprasannan** [comment]
@nanako-sen What you are seeing is probably behaviour differences between different revisions of appcompat-v7 library. Hotline SDK doesn't change the behaviour of ActionBarActivity or appcompat components.

What's happening here is that the SDK declares revision `22.2.1` of `appcompat-v7` and `recyclerview-v7` as a dependency. So when you include the SDK, gradle pickups the latest revision among `21.0.3` (declared in the app) and `22.2.1`(declared in Hotline SDK) which is `22.2.1` of the of `appcompat-v7`. 

One way to fix this would be to force gradle to not include revisions of appcompat and recycler view from Hotline SDK, but pickup the versions declared in the app. This can be achieved by including the SDK as follows in your app's build.gradle.

```
compile 'com.android.support:appcompat-v7:21.0.3'
compile 'com.android.support:recyclerview-v7:21.0.3'
compile ('com.github.freshdesk:hotline-android:1.0.+') {
        exclude group: 'com.android.support'
}
```

This should fix it. If you are still facing issues, please let us know.

You can run the following gradle command to print the dependency graph which will list all the dependencies and the specific versions that is being used to build the app.

```
./gradlew -q :app:dependencies --configuration compile
```

**Comment by tryprasannan** [comment]
Switching to the right appcompat-v7 revisions should have fixed this, if you're still facing this, please feel free to reopen.
